{% set name = "globus-cli" %}
{% set version = "3.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3f107119e93506d699f59e41942a20c4a373042f63343bac593874bc190a3a82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.1
    - pip
  run:
    - python >={{ python_min }}
    - globus-sdk ==3.63.0
    - click >=8.1.4,<8.3
    - jmespath ==1.0.1
    - packaging >=17.0
    - requests >=2.32.3,<3.0.0
    # for all python to keep the recipe noarch: python
    - typing_extensions >=4.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - globus_cli
    - globus_cli.commands
  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
