{% set name = "globus-cli" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/globus/globus-cli/archive/{{ version }}.tar.gz
  sha256: c779e31acd173b0402cd08691a47cee22da2420ad2ed337b4620891ebf9999f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - globus = globus_cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - globus-sdk 3.0.1
    - click >=8.0.0,<9
    - jmespath 0.10.0
    - requests >=2.0.0,<3.0.0
    - cryptography >=1.8.1,<35.0.0

test:
  requires:
    - pip
  imports:
    - globus_cli
    - globus_cli.commands
    - globus_cli.commands.bookmark
    - globus_cli.commands.config
    - globus_cli.commands.endpoint
    - globus_cli.commands.endpoint.permission
    - globus_cli.commands.endpoint.role
    - globus_cli.commands.endpoint.server
    - globus_cli.commands.task
    - globus_cli.helpers
    - globus_cli.parsing
    - globus_cli.safeio
    - globus_cli.services
  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
    - lukaszlacinski
