{% set name = "globus-cli" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/globus-cli-{{ version }}.tar.gz
  sha256: a93abd8583ea10f6df8fae84e17b5b253b9bb7d563fa09f8eaad0c3a3b8e95eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - globus = globus_cli:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - globus-sdk 3.16.0
    - click >=8.0.0,<9
    - jmespath 1.0.1
    - requests >=2.19.1,<3.0.0
    - cryptography >=3.3.1,<37
    - typing-extensions >=4.0

test:
  requires:
    - pip
  imports:
    - globus_cli
    - globus_cli.commands

  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
    - lukaszlacinski
