{% set name = "globus-cli" %}
{% set version = "3.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/globus/globus-cli/archive/{{ version }}.tar.gz
  sha256: b7b1c4936c0cff2ea6fed38a2178d0df8ac2f95ebfd0ef44e08b8d2323818548

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - globus = globus_cli:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - globus-sdk 3.1.0
    - click >=8.0.0,<9
    - jmespath 0.10.0
    - requests >=2.19.1,<3.0.0
    - cryptography >=3.3.1,<37

test:
  requires:
    - pip
  imports:
    - globus_cli
    - globus_cli.commands

  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
    - lukaszlacinski
