{% set name = "globus-cli" %}
{% set version = "3.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 624ca2d2447b1383d67fdc6a9fe733890c266ab90c9c0d171c7343f33b203de1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - globus = globus_cli:main

requirements:
  host:
    - python >=3.8
    - setuptools >=61.2
    - pip
  run:
    - python >=3.8
    - globus-sdk ==3.41.0
    - click >=8.1.4,<9
    - jmespath ==1.0.1
    - packaging >=17.0
    - requests >=2.19.1,<3.0.0
    - cryptography >=3.3.1
    # for all python to keep the recipe noarch: python
    - typing-extensions >=4.0

test:
  requires:
    - pip
  imports:
    - globus_cli
    - globus_cli.commands

  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
