{% set name = "globus-cli" %}
{% set version = "3.33.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a49b90ef93b28eea4f36a302f5d54e41b69bfc17fd397e1cb14aa1443f70f57d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - globus = globus_cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - globus-sdk ==3.53.0
    - click >=8.1.4,<9
    - jmespath ==1.0.1
    - packaging >=17.0
    - requests >=2.32.3,<3.0.0
    # for all python to keep the recipe noarch: python
    - typing_extensions >=4.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - globus_cli
    - globus_cli.commands
  commands:
    - globus --help
    - pip check

about:
  home: https://github.com/globus/globus-cli
  summary: Globus CLI
  description: A Command Line Interface to Globus.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://globus.github.io/globus-cli
  dev_url: https://github.com/globusonline/globus-cli

extra:
  recipe-maintainers:
    - xylar
