travis:
  secure:
    BINSTAR_TOKEN: ZQjq3fVF2gMKV7fVEuEz0UEVM34ns6G0Z1eUsYgObnEK5U6vcMtSETwiKFJ5HDG8f8l8PM1UK/40dd28WykkzSYvktLF8DHgtLqilxWOGS8KAlDYwtNPJtdWYwGSdg0I//0Rua4EFNu6y0elov8W+FawRxvyD5x8yccaxxvEKZqU0da88dRN2Fyq5Dhpj//mSyDcDKfFQwlIBXRfVwUZHd8ZKKEa2FrXxulzLSopmtKaQWoA3ioatqxRiP45RcpkksUTahkNXMQR9Lx3KP7zQ+Tuo2iaDpfmcsmj30wp0JCSh8tUWYVKtSPzJTPZjhGWkMDei+nHGT4epUTYE+y+SUGx0lAKw8332oikePq9j7LnsBhpNiNn5jqN/z3GS6QdRMB2dVpb0SHraiMwWtLHQ77+1K/m7aqwDvzE+cFFpoRS8Dlt936+suj68rHWR7LXoFrc/pPS60fQqUqq0L6xY8b0eeohRPGFm03ztTCamgANdV7S7t+w+wGCiCmzWEYrqV1G3vjY+sWfNV7azvbma5nqbNIXbDIPvL3nUj7p6o9c6wjbfeSl3dTyqzpoXRaxxQRtMsu6FXeuYi+huovL27x4Y4sOXG/dhFZgc28D4yqtBHRZqQrah+roA95wT+o6lsREWZhILls3H6X9nW5SDeINckgJbU1H6iZPcvBKnKk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
